# Generated by Django 5.1.7 on 2025-04-24 21:19

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCalendario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio', models.TimeField(default=datetime.time(0, 0))),
                ('hora_fin', models.TimeField(default=datetime.time(12, 0))),
                ('salon', models.CharField(default='Sin salón asignado', max_length=100)),
            ],
        ),
    ]
