# Generated by Django 5.1.7 on 2025-04-24 21:19

import formulario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(help_text='Formato: V o E seguido de 6 a 8 dígitos (ej: V123456, E12345678)', max_length=9, unique=True, validators=[formulario.models.validate_id_number], verbose_name='Cédula')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('academic_degree', models.CharField(max_length=50)),
                ('state_of_residence', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10, verbose_name='Form State')),
                ('is_regulated_subject', models.CharField(choices=[('si', 'Si'), ('no', 'No')], help_text='Select if you are a regulated subject or not', max_length=3, verbose_name='Is regulated subject?')),
                ('regulated_subject_type', models.CharField(blank=True, help_text='Required if regulated subject', max_length=50, null=True, verbose_name='Regulated subject type')),
                ('intermediary_type', models.CharField(blank=True, max_length=50, null=True)),
                ('auxiliary_type', models.CharField(blank=True, max_length=50, null=True)),
                ('auditor_type', models.CharField(blank=True, max_length=50, null=True)),
                ('registration_code', models.CharField(blank=True, max_length=50, null=True)),
                ('employment_condition', models.CharField(blank=True, help_text='Required if not a regulated subject', max_length=50, null=True, verbose_name='Employment condition')),
                ('company_type', models.CharField(max_length=50)),
                ('years_of_experience', models.CharField(max_length=20)),
                ('desired_diploma', models.CharField(max_length=50)),
                ('employment_status', models.CharField(max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registration Form',
                'verbose_name_plural': 'Registration Forms',
                'ordering': ['-created_at'],
            },
        ),
    ]
